version: '2'
services:
  postgres:
    image: postgres:13
    ports:
      - 5438:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata